### ISSUE TITLE
Terraform - Quotes in variable descriptions result in invalid YAML

### ISSUE THREAD

**Issue by jritsema** [awslabs/protonizer#8]
Quotes in Terraform variable descriptions result in invalid YAML.  For example:

```yaml
command:
  title: command
  type: array
  items:
    type: string
  description: "(optional) command to run in the container as an array. e.g. ["sleep", "10"]. If null, does not set a command in the task definition."
```
